### PR TITLE
Holon

### PR DESCRIPTION
**Pull request by scenaristeur**
Playing with shapes

### CODE REVIEW

**Comment by Mitzi-Laszlo** [comment]
Thanks @scenaristeur! 

Do you have a link to the source code and license? 

Also is it ok if we start a dedicated thread on the forum for user support? Curious to understand what kind of support users can expect?

**Comment by scenaristeur** [comment]
@Mitzi-Laszlo the source is here . https://github.com/scenaristeur/holon
Well about licence, I don't know, 
Something like "hey if you like it say and share, if you improve it share, and if you get some money with it, please give me a buck to help me do more stuff like that" .
Does this licence exist ? 😊

**Comment by Mitzi-Laszlo** [comment]
What you can do is take the standard text of, for example, the MIT license and adapt it to your app and pop it in a LICENSE.md file. 

Here is an example of that https://github.com/Arquisoft/dechat_en1b/blob/master/LICENSE

**Comment by Mitzi-Laszlo** [comment]
Perhaps we could open a thread in the forum dedicated to conversations about Holon for users to be able to contact you and ask questions about Holon?

**Pull request merged**
