### PR TITLE
Use @timbl's tagline

### LINKED ISSUE #239: Change home page motto to first para of TBL vision

### PR DESCRIPTION
**Pull request by Vinnl**
@timbl wanted to use the following as the tagline for the homepage, so this PR adds that:

>  Solid is a technology, like the Web, but a new level of standard which adds to the existing protocols to make it more powerful, particularly to empower individuals at home and at work.

Fixes #239.

### CODE REVIEW

**Comment by csarven** [comment]
I like the simplicity of "at home and at work" but thinking that perhaps it is limiting. Is it particularly about those locations and potential activities? How about "anywhere" eg. they may be outdoors for leisure - as long as they are connected?

**Comment by Vinnl** [comment]
Tim is now suggesting

> The Web, take 3

**Comment by RubenVerborgh** [comment]
> The Web, take 3

That means 1000 different things to 100 different people.

**Comment by timbl** [comment]
Not contentful?  but spiritfull.  We can link it to a small page which discusses why web 1 web 2 web3

**Comment by timbl** [comment]
Lets go with "The Web - Take 3" .

**Comment by RubenVerborgh** [comment]
I really don't see how that informs anyone. Plus, Web 3.0 and 4.0 have been claimed many times by many others.
It adds confusion without adding content.

**Comment by timbl** [comment]
Merging as we are out time pressure to get a new home page out.  Happy to look at different takes on this in future.

**Comment by Vinnl** [comment]
@timbl I've updated it with "Take 3" being a link to the page with a description of your "take 3", but the link colour doesn't work quite well yet against the dark background. I'll have to update that when I have time.

**Pull request merged**
