### PR TITLE
import solid-idps

### PR DESCRIPTION
**Pull request by bourgeoa**
@michielbdejong 
 import solid-idps in `solidproject.org/solid-idps` issue #412

### CODE REVIEW

**Review by justinwb — CHANGES_REQUESTED** [review]
This approach was a suggestion from another issue thread - it hasn't been accepted as a path forward at this point.

**Comment by bourgeoa** [comment]
No problem. The code is made available. That was the only purpose of the PR.

**Comment by KyraAssaad** [comment]
@bourgeoa do you want to leave this PR open for reference? Or should we close it?

**Comment by bourgeoa** [comment]
Shall be closed

**Pull request closed without merging**
