### PR TITLE
add Assemblage project

### PR DESCRIPTION
**Pull request by mfornos**

### CODE REVIEW

**Comment by Vinnl** [comment]
It looks great @mfornos! However, is it actually available somewhere so that people can actually run it? (I tried it locally but ran into an error, but I'll report that in the repository directly.)

**Comment by mfornos** [comment]
Thank you for the feedback @Vinnl.

Right now it's not hosted in any pubic server. 

We will check out the error when you report it :smile:

**Comment by NSeydoux** [comment]
@mfornos, @Vinnl , has the issue been reported, and possibly fixed ? Is it possible to have a link to the issue tracker here to make merge this PR in when the problem is resolved :) ?

**Comment by mfornos** [comment]
@NSeydoux of course. Was reported and fixed. Link: https://gitlab.com/omd_public/assemblage/-/issues/1

**Comment by mfornos** [comment]
@NSeydoux the problem was already resolved, the link to the issue is https://gitlab.com/omd_public/assemblage/-/issues/1
Any update on this? :cat:

**Comment by mfornos** [comment]
@Vinnl @NSeydoux any news on this addition? Is just a link and all the requirements were fulfilled long time ago... 😀

**Review by Vinnl — APPROVED** [review]
Oops, I must have forgotten the relation of the ticket I created earlier to this one. Would still be great if it was hosted somewhere so people could try it even if they're not familiar with Docker or Node, but with our current criteria I guess this is fine.

**Pull request merged**
