### PR TITLE
2023 redesign

### PR DESCRIPTION
**Pull request by michielbdejong**
Another rebase, this time using https://github.com/solid/solidproject.org/commits/convert-to-static/ which means URLs like [/newsletter/2021-08-12](https://solidproject.org/newsletter/2021-08-12) will remain preserved for deeplinking (but with a notice saying this is historical content, since we no longer have a newsletter).

Intend to merge during the 12 June team meeting.

The [notice about contributing](https://github.com/solid/solidproject.org?tab=readme-ov-file#important-note-about-2023-redesign) stays true: while this PR is open, all other contributions should be made against the `2023-redesign` branch. Any contributions that arrive after the merge of this PR should then be made or rebased to the `main` branch again.

### CODE REVIEW

**Comment by michielbdejong** [comment]
Main:
Screenshot 2024-05-02 at 09 32 23
For users:
Screenshot 2024-05-02 at 09 32 46
For developers:
Screenshot 2024-05-02 at 09 33 15
For organisations:
Screenshot 2024-05-02 at 09 33 22
Community:
Screenshot 2024-05-02 at 09 33 36

**Comment by melvincarvalho** [comment]
> Intend to merge during the 12 June team meeting.

LGTM!

**Comment by michielbdejong** [comment]
Staging this here: https://solidproject-org-staging.liquiddata.dev/

**Comment by michielbdejong** [comment]
Hm weird,
https://app.netlify.com/sites/solidproject-dot-org/deploys/665d8de5e1046f0008daa66c fails to install dependencies
Even though https://app.netlify.com/sites/musical-sawine-26ffa9/deploys/665d8b409dc7060008954ace succeeds.
We can reinstall Netlify on the repository to fix this, something we can work out during next week's Solid Team meeting.

**Comment by michielbdejong** [comment]
As discussed in [yesterday's team meeting](https://github.com/solid/team/blob/main/meetings/2024-06-12.md#website-go-live), we're waiting for some more edits from Giselle and colleague (hopefully today), then will rebase and merge.

**Comment by gisellewenban** [comment]
> As discussed in [yesterday's team meeting](https://github.com/solid/team/blob/main/meetings/2024-06-12.md#website-go-live), we're waiting for some more edits from Giselle and colleague (hopefully today), then will rebase and merge.

Yes I am still working on it with my colleague right now - thanks for your patience. I will update once ready

**Comment by michielbdejong** [comment]
I'm rerunning https://github.com/solid/solidproject.org/actions/runs/9462085797 so we can rebase on the gh-pages artifact from that, instead of https://github.com/solid/solidproject.org/commit/f8c42ca15fe7e9316c6bb91844d4ed90d6470132 which is now outdated.

**Pull request merged**
