### PR TITLE
Add shighl

### PR DESCRIPTION
**Pull request by scenaristeur**

### CODE REVIEW

**Comment by Vinnl** [comment]
@jeff-zucker Do you know why we have both https://github.com/solid/solidproject.org/blob/staging/_posts/for-developers/apps/tools/2019-01-01-00_overview.md and https://github.com/solid/solidproject.org/blob/staging/_posts/for-developers/apps/tools/2020-01-25_overview.md? The latter was created by you I see, but is not visible because it has the same URL as the former - should its contents be merged into the former?

**Comment by jeff-zucker** [comment]
> @jeff-zucker Do you know why we have both [2019-01-01-00_overview.md](https://github.com/solid/solidproject.org/blob/2b2850c06cc1227c906f20f6d81dcc1b48fc90df/_posts/for-developers/apps/tools/2020-01-25_overview.md) and [2020-01-25_overview.md](https://github.com/solid/solidproject.org/blob/2b2850c06cc1227c906f20f6d81dcc1b48fc90df/_posts/for-developers/apps/tools/2019-01-01-00_overview.md)? The latter was created by you I see, but is not visible because it has the same URL as the former - should its contents be merged into the former?

Thanks for catching this and sorry for not responding, for some reason, I do not always get github notices, grab me on gitter if I don't respond.   I would like to merge the older version into mine - basically keep the structure of mine,  but add in the couple of missing libs on the other one.  Does that sound OK?  If so, should I submit it as a PR on the other version?

**Comment by Vinnl** [comment]
Thanks. Yep, the other version is the one that's shown on the website, so submitting it to that works. You're probably best suited to know what the final version should look like, so I'd much appreciate it if you'd want to take the lead in that :)

**Comment by jeff-zucker** [comment]
I've added Shighi and several others to the [staging area](https://github.com/solid/solidproject.org/blob/staging/_posts/for-developers/apps/tools/2019-01-01-00_overview.md),  I asked for feedback in the chat and forum.  Once the dust settles, I'll create a PR.

**Comment by Vinnl** [comment]
Thanks a lot Jeff, very helpful. And if I could make one request for future changes: could you create a branch with the proposed changes, and then create the PR from that branch to `staging`? The reason for that is that `staging` is automatically deployed to solid.github.io, but only if all checks pass - which a PR shows:

image

Now the deployment was broken (don't worry, that happens easily - it goes through a spellcheck that doesn't know words like "Molid"). I fixed it manually now, but ideally we catch these things _before_ they break things :)

**Comment by jeff-zucker** [comment]
Ah, okay, I thought I could commit to staging and then later do a PR for the final.  So I will wait a bit more for input, then make a branch of staging and commit there.

**Pull request merged**
