### PR TITLE
Improve Copy Brainstorm

### PR DESCRIPTION
**Pull request by Mitzi-Laszlo**
Here I invite you to have a brainstorm around how to make "Apps that give you the freedom to move" more about interoperability.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
(Unassigned because not ready for review.)

**Comment by Mitzi-Laszlo** [comment]
Will leave this pull request open for a few more days and then will close if there are no concrete suggestions. Anyone can always open another pull request if there are concrete suggestions further down the line.

**Comment by RubenVerborgh** [comment]
Usually these things work better as issues. E.g., we create an issue "Improve copy brainstorm", in which we briefly sketch what needs improving.

Then the issue remains open until it is fixed; and fixing can be done with pull requests.

**Comment by Mitzi-Laszlo** [comment]
Thank you @NSeydoux :)

**Pull request closed without merging**
