### PR TITLE
added solidweb.org to servers

### PR DESCRIPTION
**Pull request by ewingson**
@Mitzi-Laszlo @jaxoncreed @Vinnl @NSeydoux @timbl @melvincarvalho 

I think we should also list
- solid.community
- dev.inrupt.net as experimental

what do you think ?

### CODE REVIEW

**Comment by Vinnl** [comment]
@Mitzi-Laszlo I think there were some criteria you maintained for servers on this list w.r.t. support and SRE's? Could you take a look at this PR and/or list those criteria somewhere on the website?

**Comment by ewingson** [comment]
@Mitzi-Laszlo @Vinnl 

for the moment I have only one-man-support on solidweb.org.
I think it' s expression of diversity to include where we are now with POD-providers.
am maintaining solid.community together with 4 people and can change the PR. momentary we have 2 providers, think it should be five. at least I have listed technical details in the terms now and just wanted to start a discussion. we' re in an early stage and should act as a team. scientific thinking, inclusion and teamwork is tightly woven in my mind. so much for now, let' s concentrate on the tech now.

**Comment by NSeydoux** [comment]
I think it would be appropriate to add a disclaimer to remind that being listed on this page is not an endorsement by the Solid project, as it is done for the apps: https://solid.github.io/use-solid/apps. I mean absolutely no offense to any of the providers (and in particular to you who submitted the PR @ewingson ), and I trust you to run you Pod server responsibly, but I think it would provide clarity to specify that anyone can run a Pod server, with no guarantee of uptime or else. @Vinnl, you mentioned criteria to qualify to be listed on the website, I think a mention of these could be featured in such disclaimer.

**Comment by ewingson** [comment]
comment and close.

**Pull request closed without merging**
