### PR TITLE
Update press.md

### PR DESCRIPTION
**Pull request by FutureLearnSole**
Are people going to care enough that they’ll put up with what may feel like a temporary step back?
_Proceed_

### CODE REVIEW

**Comment by Vinnl** [comment]
@Mitzi-Laszlo This adds https://darcy.is/winning-a-mozilla-seed-award/, which is technically not about Solid directly, but about a Solid app, to the Press page. You're probably in a better position than me to judge whether that's in scope :)

**Comment by FutureLearnSole** [comment]
@Mitzi-Laszlo please, Mam?

**Comment by Mitzi-Laszlo** [comment]
At the moment, the links in Press all mention Solid at least once. So if they are about an app that uses Solid, for example, they are also listed on the press page.

**Comment by Vinnl** [comment]
OK, there are some conflicts - if you can resolve those (or give us access to resolve them), this can be merged.

**Comment by FutureLearnSole** [comment]
nod https://github.com/solid/solidproject.org/pull/320#issuecomment-675440057
hold blame
1. 
2. https://github.com/solid/solidproject.org/commit/1fc17e2b56068a603c687b52b8d4e8beb3581b93#r41486805
3. https://github.com/solid/solidproject.org/commit/e917d89465da6e9b5b6bd929f2841b06e1294f30#r41487016
update branch
### mark ready

**Review by Vinnl — APPROVED** [review]

**Pull request merged**
