### PR TITLE
Correct all other mentions suggesting Solid would be a standard

### PR DESCRIPTION
**Pull request by RubenVerborgh**
Following the acceptance of #26, this PR now corrects all remaining mentions of "is a standard".

This PR also retroactively corrects the _This week in Solid_ newsletters. I understand there could be arguments against changing the historical record, but I think spreading misinformation might be worse. Furthermore, the record is preserved here on git, and the text itself was more header/boilerplate rather than unique per newsletter.

### CODE REVIEW

**Comment by NSeydoux** [comment]
I don't think updating previous issues of TWiS is a problem. However, in the past the use of the word 'ecosystem' was deemed a too vague by the users during user testing, which contributed to a general sentiment that Solid might be more about the hype than the technology. 

We already discussed this, so I know your motivation is to show that Solid is not only about the standard, but also about its implementations, and the apps relying on it. Maybe a way to address that would be to define Solid as an 'aspiring open standard' or as an 'open set of specifications, based on existing standards', which gives a clear, focused depiction of what Solid is, and describe the spec+its implementations+the apps as 'the Solid ecosystem'. In that sense, Solid would stil be the spec, but we would recognize the importance of the ecosystem.

**Comment by Mitzi-Laszlo** [comment]
@RubenVerborgh it would be best if you raise this directly with Tim. ["Solid is a standard" is a quote.](https://github.com/solid/Explaining-the-Vision-Panel#solid-is-a-standard-for-a-generic-data-store-api--data-storage)

**Comment by RubenVerborgh** [comment]
@Mitzi-Laszlo I urge you to follow the process. There is nothing in the process that gives the Community Manager the authority to close PRs. Also, Tim is only involved when the staging site is brought into master; staging requests only need creator approval.

For the argumentation of why "standard" is incorrect, please see the FAQ in the already accepted PR https://github.com/solid/solidproject.org/pull/26.

Regarding the quote by Tim that you have referred to multiple times now: as explained to you in the past, just a couple of sentences later, he refers to "standards" in plural. Cherry-picking is not helpful.

**Comment by RubenVerborgh** [comment]
@NSeydoux Thanks, agreed and will update accordingly. My motivation here is solely to get inaccuracies out of the text, I have no strong opinion on phrasing at this time, so will follow your suggestion.

**Comment by RubenVerborgh** [comment]
@NSeydoux Updated taking your suggestions into account.

Note that the main reason for this PR is technical accuracy; it is very likely that better phrasings exist for marketing purposes.

**Comment by RubenVerborgh** [comment]
Following the process at https://github.com/solid/process#solidprojectorg-website and given approval by a Creator, I have merged this PR to `staging`.

**Pull request merged**
