### PR TITLE
Fix broken table formatting in markdown file

### PR DESCRIPTION
**Pull request by inseo24**
https://solidproject.org/apps 

image

### CODE REVIEW

**Review by Vinnl — COMMENTED** [review]
Oops, thanks for catching that @inseo24! Unfortunately, this fix doesn't seem to be enough to fix the table; you can see changes you push to your branch at https://deploy-preview-771--solidproject-dot-org.netlify.app/apps. Would you like to see if you can fix potential other problems too, or shall I try?

**Comment by inseo24** [comment]
I've added the description, but if there's still an issue, it would be great if you could help out. Thanks!

**Comment by inseo24** [comment]
i'll try more!

**Comment by inseo24** [comment]
I fixed it!

**Review by Vinnl — APPROVED** [review]
Fantastic, thank you so much! (Also, it broke just because there was no empty line between a heading and the table? Darnit :laughing: )

**Pull request merged**
