### PR TITLE
Add recent podcast episodes to the press page and the newsletter

### PR DESCRIPTION
**Pull request by Vinnl**
@angelo-v @VirginiaBalseiro pinging you that you both are OK with being listed on the "in the press" page (and for Virginia in the newsletter), and whether the links for your names point to where you'd like them to point.

Press page preview: https://deploy-preview-481--solidproject-dot-org.netlify.app/press (newsletter wouldn't be published yet)

### CODE REVIEW

**Review by VirginiaBalseiro — APPROVED** [review]

**Comment by angelo-v** [comment]
Yes, totally fine. While reviewing I just saw a UTF-8 error in my talk "DIE RÃ¼CKEROBERUNG DES SOCIAL WEB" it should be a german `Ü` instead of `Ã¼`

**Comment by Vinnl** [comment]
Thanks @angelo-v. Could you point me to where that error is? I'm having trouble spotting it:

image

**Comment by angelo-v** [comment]
It is in the already existing code:

image

**Comment by Vinnl** [comment]
@angelo-v Got it. Lowercase, I presume? https://github.com/solid/solidproject.org/pull/482

**Review by NSeydoux — APPROVED** [review]
Great contributions, thanks !

**Pull request merged**
