### PR TITLE
update term list and add some links

### PR DESCRIPTION
**Pull request by bourgeoa**

### CODE REVIEW

**Comment by bourgeoa** [comment]
@jeff-zucker  I have no write access to add reviewers

**Comment by jeff-zucker** [comment]
@bourgeoa  , I have put the entire glossary into RDF.  I need to discuss where that document will live as a source of truth.  Once we have done that, editing can occur on the RDF.  I will add your last PR by hand.  I will put up the RDF and the generated HTML in the next day or so. **Please do not submit any more changes until I have uploaded the most recent materials.**

**Comment by bourgeoa** [comment]
Ok

**Comment by jeff-zucker** [comment]
@bourgeoa - I should have added - thanks for gathering those, I much appreciate your contribution.  I'll have a version you can do normal PRs on very soon.

**Comment by KyraAssaad** [comment]
@jeff-zucker Should we merge this now or do you want to cancel it so we can link your glossary properly?

**Comment by jeff-zucker** [comment]
Sorry, I'll PR my fuller glossary as soon as I can.

**Pull request closed without merging**
