### PR TITLE
Pod Provider Link not Loading

### PR DESCRIPTION
**Pull request by Mitzi-Laszlo**
https://solid.authing.cn is resulting in a 504 Gateway Time-out error page. With this pull request, I propose to de-list the Pod provider until the link is repaired.

### CODE REVIEW

**Comment by Mitzi-Laszlo** [comment]
yes

**Comment by csarven** [comment]
Alright, okay to remove. Might want to share the URL of the notice here for the sake of process and provenance.

**Comment by Mitzi-Laszlo** [comment]
The conversation with the Pod provider was done via email so tricky to provide link.

**Comment by csarven** [comment]
Per https://github.com/solid/solidproject.org/blob/81d53da912d360a032a194f30848b0f62e78c9aa/pages/use-solid/apps.md :

>If you believe one of the apps below is insecure or non-functional and should be removed from the list, please raise an issue here and tag the app's creator or maintainer. If the creator or maintainer of the app does not respond within 24 hours to indicate that they will fix the problem, a Solid Creator will remove the app from the listing.

I believe the context is apps.md which includes pods, and not strictly "Solid apps". Otherwise, text needs to be updated to capture pods as well. Without that, there is no process to (de)list pods.

That aside, why wasn't there an issue to reach out to the creator or maintainer of authing.cn?

Additions and removals should be publicly readable and referenceable.

Lastly, why wasn't the email exchange to remove indicated in this PR to begin with?

**Comment by csarven** [comment]
@leinue @yelexin @kelvinji2009 @liaochangjiang et al. can you please acknowledge this PR with a comment here. Thanks.

**Comment by leinue** [comment]
We have some server problems, we will fix this as soon as possible.

**Pull request merged**
