### PR TITLE
Validate HTML on Travis

### PR DESCRIPTION
**Pull request by RubenVerborgh**
This PR installs an HTML validation hook.

Currently fails because of this invalid HTML:
- https://github.com/solid/solid.github.io/blob/ff9b1580f65c317676d12e98f74a44a20a3dea5a/for-developers/apps/vocabularies/publish.html#L190

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Mmm now our staging build is broken though.

**Comment by Vinnl** [comment]
I was hoping to fix it immediately afterwards, assuming it would be just the one chang you mentioned. If fixing the other errors is not possible in the short term (see https://github.com/solid/solidproject.org/pull/95#issuecomment-566127674), could you let me know? Then I'll revert this.

**Comment by RubenVerborgh** [comment]
Now there sure were a lot of errors to be fixed: 296d8b66201f93111cbf1cb8629d3c14cbfb77b7 🙂

**Comment by Vinnl** [comment]
Doing the Lord's work, thanks @RubenVerborgh :)

One question though: why did you add the square brackets in `alt` attributes? Does that signify something special to screen readers? Because otherwise I'd only expect that to make life _more_ difficult for people with visual impairments?

Additionally, do you think it would be possible to exclude This Week in Solid posts (other than `next.md`) from the checks? Links there are more likely to get outdated at some point in time, but changing them after the fact (like you needed to do now for the "Tasks" entries) doesn't seem right, or worth the effort, either...

**Comment by RubenVerborgh** [comment]
> why did you add the square brackets in `alt` attributes?

I was trying to find a good source for this, but failed. The practice used to be that square brackets are meant for descriptions, whereas regular text is replacement text. In order to distinguish missing alt texts from those that have not been written yet, I annotated ornamental images with an empty description.

Different options are possible here for sure.

> Additionally, do you think it would be possible to exclude This Week in Solid posts

Possible, yes; desired, unsure. I indeed needed to decide between historical integrity or quality, and chose the latter (also for spelling in https://github.com/solid/solidproject.org/pull/96, since the weeklies contained several typos).

Multiple options are possible here as well. In any case, I don't think a 404 is useful for anyone, so one alternative could be to drop the links.

Since we still have git history, I chose the path of fixing the build faster over agreement on the details; we can still improve further.

**Comment by Vinnl** [comment]
> I was trying to find a good source for this, but failed. The practice used to be that square brackets are meant for descriptions, whereas regular text is replacement text. In order to distinguish missing alt texts from those that have not been written yet, I annotated ornamental images with an empty description.

Alright, I just double-checked with my screen reader, and square brackets seem to just be ignored, so I think we're good here.

> I don't think a 404 is useful for anyone, so one alternative could be to drop the links.

They can be useful for knowing which URL to insert into archive.org, but I see your point :)

(Spelling should not be a problem either way, since that won't break after fixing it, so with the spell checker now added to CI, it should not affect past issues going forward.)

**Pull request merged**
