### PR TITLE
patch-77

### PR DESCRIPTION
**Pull request by FutureLearnSole**
- [x] Disallow edits by maintainers
<hr>
**lfgtm**

- [x] [is-skrollable-mobile](./466) 
- [x] [to-tissue](https://github.com/solid/solidproject.org/issues/422)
- [x] [deploy--466](https://deploy-preview-466--solidproject-dot-org.netlify.app/users/get-a-pod)

### CODE REVIEW

**Review by NSeydoux — APPROVED** [review]

**Comment by NSeydoux** [comment]
Is there a reason why this PR is in draft state, or shall I move forward and merge it ?

**Comment by FutureLearnSole** [comment]
yes please

**Comment by NSeydoux** [comment]
Since edits by maintainers are disabled, I can't rebase this branch on master nor merge master in it. Could you do it so that I can merge please ?

**Comment by FutureLearnSole** [comment]
exp

**Pull request closed without merging**
