### PR TITLE
Added SNS

### PR DESCRIPTION
**Pull request by ElectraPro-pk**
[**SNS**](https://electrapro-pk.github.io/SNS/) developed by a  [team](https://bscs16sdp20.wixsite.com/snss) of [Foundation University Islamabad, Rawalpindi Campus (FURC)](http://furc.fui.edu.pk/) as Final Year Project under supervision of [Dr.Shariq Hussain](http://furc.fui.edu.pk/media/fcv_S/dr%20shariq.html) and [Mr. Umar Mahmud](http://furc.fui.edu.pk/media/fcv_S/Ms.Umar%20Mehmmod.html).

The main issue faced by the users while using any social networking website is that the data is not owned by them. While the user himself is the owner of that data. The user’s data including files, pictures etc. is stored at the data center or data server of the application without the user knowing where his data resides. 
SNS (Social Network Using SOLID) caters all privacy related issues faced by users while using any social networking application. Socially Linked Data (SOLID) architecture is used in the development of SNS that helps the user decide where his data is being stored. It promotes the concept of true data ownership and allows the user to control permissions as well as who can view or share the data by using his personal database known as Personal Online Data (POD). 
The project includes eight modules, authentication, profile privacy, friend list management, cloud data management, file sharing, chat, feedback management and report generation. 
Upon opening the application, user is asked to sign up if his/her account does not exist and a unique POD is generated that will be connected to his account through a web-id otherwise the user is asked to login to manage the account. POD is used as database/data storage for user’s data including files, posts, pictures, messages, comments, likes etc.  The user can manage the POD as well like user can edit, delete, append, update etc. The goal is to provide the user with true data ownership, reusability of data and modular design.

### CODE REVIEW

**Comment by ElectraPro-pk** [comment]
I did what you said

**Comment by ElectraPro-pk** [comment]
Sir my application is not listed in the SOLID Apps ..? how to do it .. i did what all the steps you told me

**Comment by michielbdejong** [comment]
Hi @ElectraPro-pk it takes a while (I think up to about 1 week probably) before changes move from staging to live.
@NSeydoux do you know where the staged version can be viewed and when the next deploy to live is planned?

**Comment by NSeydoux** [comment]
Absolutely. Your app appears on the [website staging version](https://solid.github.io/use-solid/apps), but validation from staging to live is a manual process involving the standard editors, so it may not happen directly. Your changes are in though, so they will be part of the next batch :)

**Comment by ElectraPro-pk** [comment]
Ok sir

**Pull request merged**
