### PR TITLE
List orgs

### LINKED ISSUE #851: Missing organizations in redesign
I'm looking over the list of organizations in the new redesign, and currently there's only BBC Research & Development listed there.

Which organizations should we list here?

### PR DESCRIPTION
**Pull request by michielbdejong**
Fixes #851

### CODE REVIEW

**Comment by michielbdejong** [comment]
Preview:
Screenshot 2024-04-29 at 23 21 24

**Comment by TallTed** [comment]
It certainly looks good on a large, lanscape viewport. How does it look in portrait on a tablet-sized, or a phone-sized viewport? The WebDeveloper browser extension can show you a bunch of viewport sizes, so you can see what is likely to happen...

**Comment by michielbdejong** [comment]
looks ok too!

**Comment by michielbdejong** [comment]
looks ok too! 
Screenshot 2024-05-02 at 09 11 57

**Pull request merged**
