### PR TITLE
Fix/94 malformed html menu

### LINKED ISSUE #94: Fix malformed HTML in navigation menu

### PR DESCRIPTION
**Pull request by NSeydoux**
Resolves #94 

Fixes issue identified in #93.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Seems like the Travis CI hook needs some more work. Could we restrict this PR to just the HTML fix? Then I will follow up in #93.

**Comment by Vinnl** [comment]
@RubenVerborgh Ah sorry, saw that just after merging. Might be best to fix the detected issues along with setting up the hook, to be able to confirm that it works. Let me know if you can get around to it shortly, otherwise I'll revert the merged #93 first.

**Comment by RubenVerborgh** [comment]
I can get to it tonight, yes.

**Comment by RubenVerborgh** [comment]
I'd suggest to "rebase and merge" this one.

**Comment by RubenVerborgh** [comment]
Merged this one for my own convenience, so I can work on #93.

**Comment by Vinnl** [comment]
:+1:

**Pull request merged**
